name: build

on:
  push:
    branches: 
      - master

permissions: 
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Build
        run: dotnet build -c Release
      - run: gh release create $(date +'dev-%s') ./PhotoMode/dist/PhotoMode.zip -p --generate-notes
        env:
          GH_TOKEN: ${{ github.TOKEN }}
        name: Creates a release in GitHub and uploads attachments